using System.Collections.Generic;

namespace PcfExport.Models
{
    /// <summary>One row from the ISOGEN SKEY reference, used by the SKEY Mapper tool.</summary>
    public sealed record SkeyEntry(string PcfIdentification, string Description, string Skey);

    /// <summary>
    /// One end-condition connector type (page 4 of the ISOGEN reference).
    /// Used to optionally substitute the trailing 2-char placeholder (**)
    /// of a SKEY before writing it to the model.
    /// </summary>
    public sealed record ConnectorEntry(string Description, string Code);

    /// <summary>End-condition connector codes. Excludes BS (Ball and Socket) and GF (Gland) per spec.</summary>
    public static class ConnectorCatalog
    {
        public static readonly IReadOnlyList<ConnectorEntry> Entries = new ConnectorEntry[]
        {
            new("Butt Weld",            "BW"),
            new("Clamped",              "CL"),
            new("Compression",          "CP"),
            new("Flanged",              "FL"),
            new("Flared",               "FA"),
            new("Glued",                "GL"),
            new("Liner/Clamp",          "LC"),
            new("Liner Nut",            "LN"),
            new("Male Part",            "MP"),
            new("Plain End",            "PL"),
            new("Push Fit",             "PF"),
            new("Reducing Liner/Nut",   "LR"),
            new("Screwed",              "SC"),
            new("Socket Weld",          "SW"),
        };
    }

    /// <summary>
    /// Static catalog extracted from the ISOGEN SKEY reference PDF.
    /// Sections excluded: LSJE-Type Flanges, Penetration Plate Items, Nozzles,
    /// Inline Filters, Spindles, Clamped Joints. Parenthetical text stripped
    /// from descriptions.
    /// </summary>
    public static class SkeyCatalog
    {
        public static readonly IReadOnlyList<SkeyEntry> Entries = new SkeyEntry[]
        {
            // --- Flanges and Balled Joints ---
            new("FLANGE-BLIND",                  "Blind flange",                                   "FLBL"),
            new("FLANGE",                        "Flared/Loose backing flange",                    "FLFL"),
            new("FLANGE",                        "Loose backing flange",                           "FLLB"),
            new("FLANGE-REDUCING-CONCENTRIC",    "Reducing concentric flange",                     "FLRC"),
            new("FLANGE-REDUCING-ECCENTRIC",     "Reducing eccentric flange",                      "FLRE"),
            new("FLANGE",                        "Screwed flange",                                 "FLSC"),
            new("FLANGE",                        "Slip-on flange with J-type weld",                "FLSJ"),
            new("FLANGE",                        "Slip-on flange",                                 "FLSO"),
            new("FLANGE",                        "Orifice slip-on flange with tapping connection", "FOSO"),
            new("FLANGE",                        "Socket weld flange",                             "FLSW"),
            new("FLANGE",                        "Weld neck flange",                               "FLWN"),
            new("FLANGE",                        "Orifice weld neck flange with tapping connections", "FOWN"),
            new("FLANGE",                        "Lap joint ring/Stub end combined flange",        "FBSE"),
            new("FLANGE",                        "Cast/lined fixed flange",                        "FLFF"),
            new("FLANGE",                        "Cast/lined rotating flange",                     "FLFR"),
            new("FLANGE",                        "Cast/lined flange with Female gland type",       "FLGF"),
            new("FLANGE",                        "Cast/lined flange with Male gland type",         "FLGM"),
            new("FLANGE",                        "Glued connection",                               "FLGL"),
            new("FLANGE",                        "Push fit connection",                            "FLPF"),
            new("FLANGE",                        "Seal-welded flange connection",                  "FLSF"),
            new("FLANGE",                        "Seal-welded flange connection",                  "FLSM"),
            new("FLANGE",                        "Concentric reducing flange",                     "FC**"),
            new("FLANGE",                        "Eccentric reducing flange",                      "FE**"),
            new("FLANGE",                        "Jacket weld neck flange",                        "JFWN"),
            new("FLANGE",                        "Jacket slip-on flange",                          "JFSO"),

            // --- Hygienic Fittings ---
            new("CONNECTOR",                     "Male part connector butt weld",                  "MPBW"),
            new("CONNECTOR",                     "Male part connector expanded",                   "MPEX"),
            new("CONNECTOR",                     "Clamp liner butt weld",                          "LCBW"),
            new("CONNECTOR",                     "Clamp liner expanded",                           "LCEX"),
            new("CONNECTOR",                     "Backing nut liner butt welded",                  "LNBW"),
            new("CONNECTOR",                     "Backing nut liner",                              "LN"),
            new("CONNECTOR",                     "Backing nut reducing liner butt weld",           "LRBW"),
            new("CONNECTOR",                     "Backing nut reducing liner expanded",            "LREX"),
            new("NUT",                           "Backing nut",                                    "BNUT"),
            new("CLAMP",                         "Clamp",                                          "CLMP"),
            new("MISC-HYGIENIC",                 "Drain/Vent plug",                                "DVP"),
            new("MISC-HYGIENIC",                 "Male blanking plug",                             "BM"),
            new("MISC-HYGIENIC",                 "Blank plain",                                    "BP"),
            new("MISC-HYGIENIC",                 "Reducing concentric blank boss",                 "BBC"),
            new("MISC-HYGIENIC",                 "Reducing eccentric blank boss",                  "BBE"),
            new("MISC-HYGIENIC",                 "Blank thermocouple connector",                   "BTP"),
            new("MISC-HYGIENIC",                 "Male-to-male adapter",                           "ADMM"),
            new("MISC-HYGIENIC",                 "Male-to-female adapter",                         "ADMF"),
            new("VALVE-ANGLE",                   "Two-port single level valve",                    "2Z**"),
            new("VALVE-ANGLE",                   "Two-port single level valve",                    "2D**"),
            new("VALVE-3WAY",                    "Three-port single level valve",                  "3Z**"),
            new("VALVE-3WAY",                    "Three-port single level valve",                  "3D**"),
            new("VALVE-4WAY",                    "Four-port single level valve",                   "4Z**"),
            new("VALVE-4WAY",                    "Four-port single level valve",                   "4D**"),
            new("VALVE-MULTIWAY",                "Multi-port dual level valve with D spindle",     "MD**"),
            new("VALVE-MULTIWAY",                "Multi-port dual level valve with Z spindle",     "MZ**"),
            new("N/A",                           "Separator for multi-level valve",                "DUMY"),
            new("INSTRUMENT",                    "Graduated control valve",                        "IG**"),
            new("VALVE",                         "Non-return valve",                               "NV**"),
            new("VALVE-3WAY",                    "Three-way check valve",                          "K3**"),
            new("VALVE",                         "Wide-angle cock",                                "KV**"),
            new("VALVE",                         "Pressure relief valve",                          "VZ**"),
            new("VALVE",                         "Butterfly valve",                                "ZB**"),
            new("VALVE",                         "Graduated control valve",                        "ZG**"),
            new("INSTRUMENT",                    "Pressure relief valve",                          "ZV**"),

            // --- Miscellaneous Pipe Components ---
            new("MISC-COMPONENT-ANGLE",          "Block angle",                                    "BA**"),
            new("MISC-COMPONENT",                "Expansion bellows",                              "EX**"),
            new("MISC-COMPONENT",                "Flame trap",                                     "FT**"),
            new("MISC-COMPONENT",                "Flexible hose",                                  "FX**"),
            new("MISC-COMPONENT",                "Hose coupling",                                  "CH**"),
            new("MISC-COMPONENT",                "Non-category item",                              "NC**"),
            new("MISC-COMPONENT-OFFSET",         "Block offset",                                   "BO**"),
            new("MISC-COMPONENT-RETURN",         "Block return",                                   "BR**"),
            new("MISC-COMPONENT",                "Plug",                                           "PL"),
            new("MISC-COMPONENT",                "Restrictor plate",                               "RP"),
            new("REINFORCEMENT PAD",             "Reinforcing pad",                                "RPAD"),
            new("MISC-COMPONENT",                "Sight glass",                                    "SG**"),
            new("MISC-COMPONENT",                "Slip plate",                                     "SP"),
            new("MISC-COMPONENT",                "Slip ring",                                      "SR"),
            new("MISC-COMPONENT",                "Spectacle blind",                                "SB"),
            new("MISC-COMPONENT",                "Spectacle blind",                                "OB"),
            new("MISC-COMPONENT",                "Tundish",                                        "TU**"),
            new("MULTI-PART COMPONENT",          "Multi-part component",                           "XF**"),
            new("MULTI-PART COMPONENT",          "Multi-part component",                           "XV**"),

            // --- Miscellaneous Items ---
            new("INSULATION-SYMBOL",             "Insulation symbol",                              "INPP"),
            new("FLOOR-SYMBOL",                  "Floor symbol",                                   "FLOR"),
            new("FLOW-ARROW",                    "Flow arrow",                                     "FLOW"),
            new("LOCATION-POINT",                "Location point",                                 "LOPT"),
            new("WALL-SYMBOL",                   "Wall symbol",                                    "WALL"),
            new("N/A",                           "Arrow head",                                     "AR01"),
            new("N/A",                           "Arrow head",                                     "AR02"),
            new("N/A",                           "Line break",                                     "AR04"),

            // --- Instruments ---
            new("INSTRUMENT",                    "Instrument",                                     "II**"),
            new("INSTRUMENT-ANGLE",              "Instrument angle",                               "IA**"),
            new("INSTRUMENT-OFFSET",             "Instrument offset",                              "IO**"),
            new("INSTRUMENT-RETURN",             "Instrument return",                              "IR**"),
            new("INSTRUMENT-DIAL",               "Instrument dial",                                "IDPL"),
            new("INSTRUMENT-DIAL",               "Instrument dial",                                "IDFL"),
            new("INSTRUMENT",                    "Orifice plate",                                  "OP"),
            new("INSTRUMENT",                    "Restrictor plate",                               "PR"),
            new("INSTRUMENT",                    "Rupture disk",                                   "DR"),
            new("INSTRUMENT",                    "Control valve",                                  "CV**"),
            new("INSTRUMENT-3WAY",               "Three-way control valve",                        "C3**"),
            new("INSTRUMENT-4WAY",               "Four-way control valve",                         "C4**"),
            new("INSTRUMENT-ANGLE",              "Angled control valve",                           "CA**"),
            new("INSTRUMENT",                    "Hand-operated control valve",                    "HV**"),
            new("INSTRUMENT-3WAY",               "Hand-operated three-way control valve",          "H3**"),
            new("INSTRUMENT-4WAY",               "Hand-operated four-way control valve",           "H4**"),
            new("INSTRUMENT-ANGLE",              "Hand-operated angled control valve",             "HA**"),
            new("INSTRUMENT",                    "Motor-operated control valve",                   "MV**"),
            new("INSTRUMENT-3WAY",               "Motor-operated three-way control valve",         "M3**"),
            new("INSTRUMENT-4WAY",               "Motor-operated four-way control valve",          "M4**"),
            new("INSTRUMENT-ANGLE",              "Motor-operated angled control valve",            "MA**"),
            new("INSTRUMENT-ANGLE",              "Instrument angle control valve with square indicator", "SA**"),
            new("INSTRUMENT",                    "Square indicator control valve",                 "SV**"),
            new("INSTRUMENT-3WAY",               "Square indicator three-way control valve",       "S3**"),
            new("INSTRUMENT-4WAY",               "Square indicator four-way control valve",        "S4**"),
            new("INSTRUMENT-ANGLE",              "Angled pressure reducing angle",                 "XA**"),
            new("INSTRUMENT-ANGLE",              "Pressure reducing instrument valve",             "XV**"),
            new("INSTRUMENT-ANGLE",              "Angled relief/valve instrument valve",           "RA**"),
            new("INSTRUMENT",                    "Relief/Vent instrument valve",                   "RV**"),

            // --- Pipe Blocks ---
            new("PIPE-BLOCK-FIXED",              "Fixed length pipe block",                        "PF"),
            new("PIPE-BLOCK-VARIABLE",           "Variable length pipe block",                     "PV"),

            // --- Vents ---
            new("SAFETY-DISC",                   "Rupture disk",                                   "RD"),

            // --- Traps ---
            new("TRAP-ANGLE",                    "Angle trap",                                     "TA**"),
            new("TRAP-OFFSET",                   "Offset trap",                                    "TO**"),
            new("TRAP-RETURN",                   "Return trap",                                    "TR**"),
            new("TRAP",                          "Inline trap",                                    "TI**"),

            // --- Welds ---
            new("WELD",                          "Workshop weld",                                  "WW"),
            new("WELD",                          "Dotted workshop weld",                           "WWD"),
            new("WELD",                          "Site weld",                                      "WS"),
            new("WELD",                          "Tack for site weld",                             "WST"),
            new("WELD",                          "Dotted site weld",                               "WSD"),
            new("WELD",                          "Field fit weld",                                 "WF"),
            new("WELD",                          "Tack for field fit weld",                        "WFT"),
            new("WELD",                          "Dotted field fit weld",                          "WFD"),
            new("WELD",                          "Offshore weld",                                  "WO"),
            new("WELD",                          "Tack for offshore weld",                         "WOT"),
            new("WELD",                          "Dotted offshore weld",                           "WOD"),
            new("WELD",                          "Offshore field fit weld",                        "WOF"),
            new("WELD",                          "Tack for offshore field fit weld",               "WOFT"),
            new("WELD",                          "Special site weld",                              "WSSP"),
            new("WELD",                          "Automatic workshop weld",                        "WWA"),
            new("WELD",                          "Field fit weld with shop test requirement",      "WFST"),
            new("WELD",                          "Field fit offshore dotted",                      "WOFD"),
            new("WELD",                          "Mitre weld",                                     "WM"),
            new("WELD",                          "Dotted mitre weld",                              "WMD"),
            new("WELD",                          "Erection mitre weld",                            "WMS"),
            new("WELD",                          "Dotted Erection mitre weld",                     "WMSD"),
            new("WELD",                          "Offshore mitre weld",                            "WMO"),
            new("WELD",                          "Dotted Offshore mitre weld",                     "WMOD"),
            new("WELD",                          "Mitre field fit weld",                           "WMF"),
            new("WELD",                          "Mitre tack weld",                                "WMT"),
            new("WELD",                          "Mitre field fit tack weld",                      "WMFT"),
            new("WELD",                          "Site workshop test weld",                        "WSST"),
            new("WELD",                          "Workshop shot test weld",                        "WWST"),
            new("WELD",                          "Offshore shop test weld",                        "WOST"),
            new("WELD",                          "Offshore field fit shop test weld",              "WVST"),
            new("WELD",                          "Support weld",                                   "ZSP*"),
            new("WELD",                          "Trunnion weld",                                  "ZTN*"),
            new("WELD",                          "Reinforced trunnion",                            "ZTR*"),
            new("WELD",                          "Site socket/screwed compression weld",           "XX"),
            new("WELD",                          "Site socket/screwed compression dotted weld",    "XXD"),
            new("WELD",                          "Erection seal weld",                             "WSSR"),
            new("WELD",                          "Offshore seal weld",                             "WOSR"),

            // --- Symbol Coupling ---
            new("COUPLING",                      "Coupling with glued connections",                "COGL"),
            new("COUPLING",                      "Coupling with push fit end connections",         "COPF"),
            new("COUPLING",                      "Coupling with flared end connections",           "COFA"),
            new("COUPLING",                      "Coupling with clamped end connections",          "COCL"),
            new("COUPLING",                      "Coupling with Victaulic connections",            "COVT"),
            new("COUPLING",                      "Coupling with Victaulic connections",            "COVR"),
            new("COUPLING",                      "Coupling with compression sleeve connections",   "CSCP"),
            new("COUPLING",                      "Coupling with Grayloc connections",              "COGY"),

            // --- Elbows and Bends ---
            new("ELBOW",                         "Elbow",                                          "EL**"), // manual addition — not in ISOGEN PDF
            new("ELBOW",                         "Butt weld elbow",                                "ELBW"),
            new("ELBOW",                         "Compression elbow",                              "ELCP"),
            new("ELBOW",                         "Screwed elbow with Female ends",                 "ELSC"),
            new("ELBOW",                         "Socket weld elbow",                              "ELSW"),
            new("ELBOW",                         "Screwed elbow with Male ends",                   "EBSC"),
            new("ELBOW-TEED",                    "Socket weld teed elbow",                         "ETSW"),
            new("ELBOW-TEED",                    "Screwed teed elbow",                             "ETSC"),
            new("ELBOW-TEED",                    "Compression teed elbow",                         "ETCP"),
            new("ELBOW-TEED",                    "Butt weld teed elbow",                           "ETBW"),
            new("ELBOW-REDUCING",                "Reducing elbow",                                 "ER**"),
            new("ELBOW",                         "Butt weld return elbow",                         "EUBW"),
            new("ELBOW",                         "Plain end return elbow",                         "EUPL"),
            new("BEND-TEED",                    "Flanged teed elbow",                              "BTFL"),
            new("BEND",                          "Butt weld mitre tee bend",                       "MTBW"),
            new("BEND",                          "Butt weld mitre bend",                           "MIBW"),
            new("BEND",                          "Flanged mitre bend",                             "MIFL"),
            new("BEND-TEED",                     "Mitre tee bend with plain ends",                 "MTPL"),
            new("BEND-TEED",                     "Flanged mitre tee bend",                         "MTFL"),
            new("BEND",                          "Flanged bend",                                   "BEFL"),
            new("BEND",                          "Bend",                                           "BM**"),
            new("BEND",                          "Flanged 180� return bend",                       "BUFL"),
            new("BEND",                          "Butt weld lobster bend",                         "L@BW"),
            new("BEND-TEED",                     "Butt weld lobster tee bend",                     "T@BW"),
            new("BEND",                          "Flanged lobster bend",                           "L@FL"),
            new("BEND-TEED",                     "Flanged lobster tee bend",                       "T@FL"),
            new("BEND",                          "Pulled bend",                                    "PB+D"),
            new("BEND",                          "180� pulled return bend",                        "BU+D"),
            new("BEND-TEED",                     "Pulled tee bend",                                "TB+D"),
            new("BEND",                          "Pulled bend with weld at each end",              "PBBW"),
            new("BEND",                          "180� Pulled return bend with weld at each end",  "BUBW"),
            new("BEND-TEED",                     "Pulled tee bend with weld at each end",          "TBBW"),
            new("ELBOW",                         "Bend with flared end connections",               "BEFA"),
            new("ELBOW",                         "Bend with clamped end connections",              "BECL"),
            new("ELBOW",                         "Elbow with flared end connections",              "ELFA"),
            new("ELBOW",                         "Elbow with clamped end connections",             "ELCL"),
            new("ELBOW-TEED",                    "Teed elbow with flared end connections",         "ETFA"),
            new("ELBOW-TEED",                    "Teed elbow with clamped end connections",        "ETCL"),
            new("ELBOW-REDUCING",                "Reducing elbow with flared end connections",     "ERFA"),
            new("ELBOW-REDUCING",                "Reducing elbow with clamped end connections",    "ERCL"),
            new("ELBOW",                         "Elbow with flanged gland-type end connections",  "ELGF"),
            new("ELBOW",                         "Elbow with flanged ball/socket end connections", "ELBS"),
            new("ELBOW-TEED",                    "Teed elbow with glued end connections",          "ETGL"),
            new("ELBOW-TEED",                    "Teed elbow with push fit end connections",       "ETPF"),
            new("BEND",                          "Bend with flanged ball/socket end connections",  "BEBS"),
            new("BEND-TEED",                     "Tee bend with flanged ball/socket end connections", "BTBS"),
            new("BEND",                          "Bend with flanged gland-type end connections",   "BEGF"),
            new("BEND-TEED",                     "Tee bend with flanged gland-type end connections", "TBGF"),
            new("BEND",                          "Bend with glued end connections",                "BEGL"),
            new("ELBOW",                         "Elbow with glued end connections",               "ELGL"),
            new("ELBOW",                         "Elbow with push fit end connections",            "ELPF"),
            new("BEND",                          "Bend with push fit connections",                 "BEPF"),

            // --- Couplings ---
            new("COUPLING",                      "Nipple",                                         "NRSC"),
            new("COUPLING",                      "Nipple",                                         "NBSC"),
            new("COUPLING",                      "Coupling",                                       "COCP"),
            new("COUPLING",                      "Coupling",                                       "COSC"),
            new("COUPLING",                      "Coupling",                                       "COSW"),
            new("ELBOLET",                       "Elbolet coupling",                               "CEBW"),
            new("ELBOLET",                       "Elbolet coupling",                               "CESC"),
            new("ELBOLET",                       "Elbolet coupling",                               "CESW"),
            new("COUPLING",                      "Coupling with glued end connections",            "COGL"),
            new("COUPLING",                      "Coupling with push fit end connections",         "COPF"),
            new("COUPLING",                      "Coupling with flared end connections",           "COFA"),
            new("COUPLING",                      "Coupling with clamped end connections",          "COCL"),
            new("COUPLING",                      "Coupling with Victaulic connections",            "COVT"),
            new("COUPLING",                      "Coupling with Victaulic connections",            "COVR"),
            new("COUPLING",                      "Coupling with compression sleeve connections",   "CSCP"),
            new("COUPLING",                      "Coupling with Grayloc connections",              "COGY"),

            // --- Caps ---
            new("CAP",                           "Butt weld cap",                                  "KABW"),
            new("CAP",                           "Compression cap",                                "KACP"),
            new("CAP",                           "Screwed cap",                                    "KASC"),
            new("CAP",                           "Socket weld cap",                                "KASW"),
            new("CAP",                           "Flanged cap",                                    "KAFL"),
            new("CAP",                           "Glued cap",                                      "KAGL"),
            new("CAP",                           "Push fit cap",                                   "KAPF"),
            new("CAP",                           "Flared cap",                                     "KAFA"),
            new("CAP",                           "Clamped cap",                                    "KACL"),

            // --- Crosses ---
            new("CROSS",                         "Cross",                                          "CR**"),
            new("CROSS",                         "Y-type cross",                                   "CY**"),
            new("CROSS-SET-ON or CROSS-STUB",    "Set-on cross",                                   "CRSO"),
            new("CROSS-SET-ON or CROSS-STUB",    "Set-on reinforced cross",                        "CRRF"),
            new("CROSS-SET-ON or CROSS-STUB",    "Stub in cross",                                  "CSSO"),
            new("CROSS-SET-ON or CROSS-STUB",    "Stub in reinforced cross",                       "CSRF"),
            new("CROSS-SET-ON or CROSS-STUB",    "Set-on cross",                                   "CYSO"),
            new("CROSS",                         "Cross with flared end connections",              "CRFA"),
            new("CROSS",                         "Cross with clamped end connections",             "CRCL"),
            new("CROSS",                         "Cross with glued end connections",               "CRGL"),
            new("CROSS",                         "Cross with push fit end connections",            "CRPF"),
            new("CROSS",                         "Cross with flanged ball/socket end connections", "CRBS"),
            new("CROSS",                         "Cross with flanged gland-type end connections",  "CRGF"),

            // --- Fixed Length Pipes ---
            new("PIPE-FIXED",                    "Fixed length pipe with integral ends",           "FPFL"),
            new("PIPE-FIXED",                    "Fixed length pipe without flanged ends",         "FPPL"),
            new("PIPE-FIXED",                    "Fixed pipe with flared end connections",         "FPFA"),
            new("PIPE-FIXED",                    "Fixed pipe with clamped end conditions",         "FPCL"),
            new("PIPE-FIXED",                    "Fixed pipe with glued end connections",          "FPGL"),
            new("PIPE-FIXED",                    "Fixed pipe with push fit end connections",       "FPPF"),
            new("PIPE-FIXED",                    "Fixed pipe with screwed end connections",        "FPSC"),
            new("PIPE-FIXED",                    "Fixed pipe with socket end connections",         "FPSW"),
            new("PIPE-FIXED",                    "Fixed pipe with compression end connections",    "FPCP"),
            new("PIPE-FIXED",                    "Fixed pipe with flanged ball and socket",        "FPFL"),

            // --- Tees ---
            new("TEE",                           "Tee",                                            "TE**"),
            new("TEE-SET-ON or TEE-STUB",        "Set-on tee",                                     "TESO"),
            new("TEE-SET-ON or TEE-STUB",        "Set-on reinforced tee",                          "TERF"),
            new("TEE-SET-ON or TEE-STUB",        "Stub in tee",                                    "TSSO"),
            new("TEE-SET-ON or TEE-STUB",        "Stub in reinforced tee",                         "TSRF"),
            new("TEE",                           "Socket weld tee",                                "TESW"),
            new("TEE",                           "Swept branch tee",                               "TSBW"),
            new("TEE",                           "Swept branch tee",                               "TSFL"),
            new("TEE",                           "Swept socket weld tee",                          "TSSW"),
            new("TEE",                           "Swept compression tee",                          "TSCP"),
            new("TEE",                           "Ghost tee",                                      "TEGG"),
            new("TEE",                           "Pulled out tee",                                 "TPUL"),
            new("TEE",                           "Offset tee",                                     "TORF"),
            new("TEE",                           "Set-on tangential tee",                         "TOSO"),
            new("TEE",                           "Tangential tee",                                 "TTRF"),
            new("TEE",                           "Offset tee",                                     "TTSO"),
            new("INSTRUMENT-TEE",                "Instrument tee",                                 "IT**"),
            new("TEE",                           "Tee with flared end connections",                "TEFA"),
            new("TEE",                           "Tee with clamped end connections",               "TECL"),
            new("TEE",                           "Tee with glued end connections",                 "TEGL"),
            new("TEE",                           "Tee with push fit end connections",              "TEPF"),
            new("TEE",                           "Tee with flanged ball/socket end connections",   "TEBS"),
            new("TEE",                           "Tee with flanged gland-type end connections",    "TEGF"),
            new("See Y-type tee/cross",          "Y-type tee",                                     "YLRG"),
            new("See Y-type tee/cross",          "Y-type tee",                                     "YMED"),
            new("See Y-type tee/cross",          "Y-type tee",                                     "YSML"),
            new("TEE",                           "Y-type tee",                                     "TY**"),
            new("TEE-SET-ON or TEE-STUB",        "Set-on Y-type tee",                              "TYSO"),

            // --- Reducers ---
            new("REDUCER-CONCENTRIC",            "Concentric reducer",                             "RC**"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric reducer",                             "CTBW"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric reducer",                             "CTSW"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer",                             "CPBW"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer",                             "CSBW"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric reducer",                             "CZBW"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric reducer",                             "CZFL"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric reducer",                             "CXBW"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer",                             "CPFL"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer",                             "CSFL"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric reducer",                             "CTFL"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric reducer",                             "CXFL"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer",                             "RNSC"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric reducer",                             "CTSC"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer",                             "RBSC"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer",                             "RBSW"),
            new("REDUCER-ECCENTRIC",             "Eccentric reducer",                              "RE**"),
            new("REDUCER-ECCENTRIC",             "Eccentric reducer",                              "EPBW"),
            new("REDUCER-ECCENTRIC",             "Eccentric reducer",                              "ESBW"),
            new("REDUCER-ECCENTRIC-TEED",        "Eccentric reducer",                              "OTBW"),
            new("REDUCER-ECCENTRIC-TEED",        "Eccentric reducer",                              "EZBW"),
            new("REDUCER-ECCENTRIC-TEED",        "Eccentric reducer",                              "EXBW"),
            new("REDUCER-ECCENTRIC-TEED",        "Eccentric reducer",                              "OTSC"),
            new("REDUCER-ECCENTRIC",             "Eccentric reducer",                              "EPFL"),
            new("REDUCER-ECCENTRIC",             "Eccentric reducer",                              "ESFL"),
            new("REDUCER-ECCENTRIC-TEED",        "Eccentric reducer",                              "OTFL"),
            new("REDUCER-ECCENTRIC-TEED",        "Eccentric reducer",                              "EZFL"),
            new("REDUCER-ECCENTRIC-TEED",        "Eccentric reducer",                              "EXFL"),
            new("REDUCER-CONCENTRIC",            "Reducing block",                                 "RFPL"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer with flared end connections", "RCFA"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer with clamped end connections", "RCCL"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric teed reducer with flared end connections", "CTFA"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric teed reducer with clamped end connections", "CTCL"),
            new("REDUCER-ECCENTRIC",             "Eccentric reducer with flared end connections",  "REFA"),
            new("REDUCER-CONCENTRIC-TEED",       "Eccentric reducer with clamped end connections", "RECL"),
            new("REDUCER-CONCENTRIC-TEED",       "Eccentric teed reducer with flared end connections", "OTFA"),
            new("REDUCER-CONCENTRIC-TEED",       "Eccentric teed reducer with clamped end connections", "OTCL"),
            new("REDUCER-ECCENTRIC",             "Eccentric reducer with glued end conditions",    "REGL"),
            new("REDUCER-ECCENTRIC",             "Eccentric reducer with push fit end connections", "REPF"),
            new("REDUCER-CONCENTRIC-TEED",       "Eccentric teed reducer with glued end connections", "OTGL"),
            new("REDUCER-CONCENTRIC-TEED",       "Eccentric teed reducer with push fit end connections", "OTPF"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer with glued end conditions",   "RCGL"),
            new("REDUCER-CONCENTRIC",            "Concentric reducer with push fit end connections", "RCPF"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric teed reducer with glued end connections", "CTGL"),
            new("REDUCER-CONCENTRIC-TEED",       "Concentric teed reducer with push fit end connections", "CTPF"),

            // --- Supports ---
            new("SUPPORT",                       "Hanger/Support",                                 "01HG"),
            new("SUPPORT",                       "Anchor",                                         "ANCH"),
            new("SUPPORT",                       "Duck foot",                                      "DUCK"),
            new("SUPPORT",                       "Guide/Steady",                                   "GUID"),
            new("SUPPORT",                       "Skid",                                           "SKID"),
            new("SUPPORT",                       "Spring",                                         "SPRG"),
            new("SUPPORT",                       "Hanger",                                         "HANG"),
            new("SUPPORT",                       "Penetration Sleeve",                             "SLVE"),

            // --- Unions ---
            new("UNION",                         "Union",                                          "UN**"),

            // --- Olets ---
            new("OLET",                          "Olet",                                           "HCSC"),
            new("OLET",                          "Olet",                                           "HCSW"),
            new("OLET",                          "Nipolet",                                        "NI**"),
            new("OLET",                          "Nipolet",                                        "NISC"),
            new("OLET",                          "Sockolet",                                       "SKSW"),
            new("OLET",                          "Sweepolet",                                      "SWBW"),
            new("OLET",                          "Thredolet",                                      "THSC"),
            new("OLET",                          "Weldolet",                                       "WTBW"),
            new("OLET",                          "Latrolet",                                       "LASC"),
            new("OLET",                          "Latrolet",                                       "LASW"),
            new("OLET",                          "Latrolet",                                       "LABW"),
            new("INSTRUMENT-TEE",                "Flanged instrument tee",                         "ITFL"),

            // --- Valves ---
            new("VALVE-ANGLE",                   "Angle valve",                                    "AV**"),
            new("VALVE-ANGLE",                   "Relief/Vent angle valve",                        "AR**"),
            new("VALVE-ANGLE",                   "Pressure reducing angle valve",                  "AX**"),
            new("VALVE",                         "Basic valve",                                    "VV**"),
            new("VALVE",                         "Check valve",                                    "VC**"),
            new("VALVE",                         "Check valve",                                    "CK**"),
            new("VALVE",                         "Ball valve",                                     "VB**"),
            new("VALVE",                         "Butterfly valve",                                "VY**"),
            new("VALVE",                         "Diaphragm valve",                                "VD**"),
            new("VALVE",                         "Globe valve",                                    "VG**"),
            new("VALVE",                         "Pressure reducing valve",                        "VX**"),
            new("VALVE",                         "Cock valve",                                     "VK**"),
            new("VALVE",                         "Gate valve",                                     "VT**"),
            new("VALVE",                         "Needle valve",                                   "VN**"),
            new("VALVE",                         "Plug valve",                                     "VP**"),
            new("VALVE",                         "Relief/Vent valve",                              "VR**"),
            new("VALVE",                         "Slide valve",                                    "VS**"),
            new("VALVE-3WAY",                    "Three-way valve",                                "V3**"),
            new("VALVE-4WAY",                    "Four-way valve",                                 "V4**"),

            // --- Liners (Connectors) ---
            new("N/A",                           "Grayloc socket weld connector",                  "LNSW"),
            new("N/A",                           "Grayloc screwed connector",                      "LNSC"),
            new("N/A",                           "Victaulic - Welded ring type",                   "LVBW"),
        };
    }
}
